/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import BaseDeDatos.BaseDeDatos;
import JFrames.Alquileres.AlquilaVehiculo;
import JFrames.Alquileres.ConsultaPrecio;
import JFrames.Alquileres.DevuelveVehiculo;
import JFrames.Clientes.BorraCliente;
import JFrames.Clientes.AltaClientes;
import JFrames.Clientes.ListaClientesInterfaz;
import JFrames.Clientes.ModificaClientes;
import JFrames.Vehiculos.ListaVehiculosInterfaz;
import JFrames.Vehiculos.AltaVehiculos;
import JFrames.Vehiculos.BorraVehiculos;
import JFrames.Vehiculos.ModificaVehiculos;
import alquilervehiculos.listas.clientes.ListaClientes;
import alquilervehiculos.listas.vehiculos.ListaVehiculos;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author vesprada
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ListaVehiculos listaVehiculos;
    private ListaClientes listaClientes;
 
    private BaseDeDatos bd;

    public Principal(ListaVehiculos listaVehiculos, ListaClientes listaClientes,BaseDeDatos bd) {

        try {
            this.listaVehiculos = listaVehiculos;
            this.listaClientes = listaClientes;
            this.bd=bd;

            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            initComponents();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuVehiculos = new javax.swing.JMenu();
        AltaVehiculosMenu = new javax.swing.JMenuItem();
        ModificacionVehiculosMenu = new javax.swing.JMenuItem();
        BorraVehiculosMenu = new javax.swing.JMenuItem();
        ListaVehiculosMenu = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenu();
        AltaClientesMenu = new javax.swing.JMenuItem();
        ModificacionClientesMenu = new javax.swing.JMenuItem();
        BorraClienteMenu = new javax.swing.JMenuItem();
        ListaClientesMenu = new javax.swing.JMenuItem();
        MenuAlquileres = new javax.swing.JMenu();
        ConsultaPrecioMenu = new javax.swing.JMenuItem();
        AlquilaVehiculoMenu = new javax.swing.JMenuItem();
        DevuelveVehiculoMenu = new javax.swing.JMenuItem();
        MenuFinanzas = new javax.swing.JMenu();
        FinanzasMenu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alquiler de vehiculos");

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1253, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MenuVehiculos.setText("Vehiculos");
        MenuVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        AltaVehiculosMenu.setText("Alta de Vehiculos");
        AltaVehiculosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaVehiculosMenuActionPerformed(evt);
            }
        });
        MenuVehiculos.add(AltaVehiculosMenu);

        ModificacionVehiculosMenu.setText("Modificacion de Vehiculos");
        ModificacionVehiculosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificacionVehiculosMenuActionPerformed(evt);
            }
        });
        MenuVehiculos.add(ModificacionVehiculosMenu);

        BorraVehiculosMenu.setText("Borrado de Vehiculos");
        BorraVehiculosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorraVehiculosMenuActionPerformed(evt);
            }
        });
        MenuVehiculos.add(BorraVehiculosMenu);

        ListaVehiculosMenu.setText("Lista de Vehiculos");
        ListaVehiculosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaVehiculosMenuActionPerformed(evt);
            }
        });
        MenuVehiculos.add(ListaVehiculosMenu);

        jMenuBar1.add(MenuVehiculos);

        MenuClientes.setText("Clientes");
        MenuClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        AltaClientesMenu.setText("Alta de Clientes");
        AltaClientesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaClientesMenuActionPerformed(evt);
            }
        });
        MenuClientes.add(AltaClientesMenu);

        ModificacionClientesMenu.setText("Modificar Clientes");
        ModificacionClientesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificacionClientesMenuActionPerformed(evt);
            }
        });
        MenuClientes.add(ModificacionClientesMenu);

        BorraClienteMenu.setText("Borrar Clientes");
        BorraClienteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorraClienteMenuActionPerformed(evt);
            }
        });
        MenuClientes.add(BorraClienteMenu);

        ListaClientesMenu.setText("Lista de Clientes");
        ListaClientesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaClientesMenuActionPerformed(evt);
            }
        });
        MenuClientes.add(ListaClientesMenu);

        jMenuBar1.add(MenuClientes);

        MenuAlquileres.setText("Alquileres");
        MenuAlquileres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ConsultaPrecioMenu.setText("Consultar precio");
        ConsultaPrecioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPrecioMenuActionPerformed(evt);
            }
        });
        MenuAlquileres.add(ConsultaPrecioMenu);

        AlquilaVehiculoMenu.setText("Alquilar vehiculo");
        AlquilaVehiculoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlquilaVehiculoMenuActionPerformed(evt);
            }
        });
        MenuAlquileres.add(AlquilaVehiculoMenu);

        DevuelveVehiculoMenu.setText("Devolver vehiculo");
        DevuelveVehiculoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevuelveVehiculoMenuActionPerformed(evt);
            }
        });
        MenuAlquileres.add(DevuelveVehiculoMenu);

        jMenuBar1.add(MenuAlquileres);

        MenuFinanzas.setText("Finanzas");
        MenuFinanzas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        FinanzasMenu.setText("Finanzas");
        FinanzasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinanzasMenuActionPerformed(evt);
            }
        });
        MenuFinanzas.add(FinanzasMenu);

        jMenuBar1.add(MenuFinanzas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltaVehiculosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaVehiculosMenuActionPerformed

        this.jMenuBar1.setEnabled(false);

        AltaVehiculos ventana = new AltaVehiculos(this.listaVehiculos, this.Escritorio,this.bd);
        ventana.setVisible(true);

        Escritorio.add(ventana);
        ventana.toFront();


    }//GEN-LAST:event_AltaVehiculosMenuActionPerformed

    private void ModificacionVehiculosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificacionVehiculosMenuActionPerformed
        ModificaVehiculos ventana = new ModificaVehiculos(this.listaVehiculos,  this.Escritorio,this.bd);
        Escritorio.add(ventana);
        ventana.toFront();


    }//GEN-LAST:event_ModificacionVehiculosMenuActionPerformed

    private void BorraClienteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorraClienteMenuActionPerformed
        BorraCliente ventana = new BorraCliente(this.listaClientes, this.listaVehiculos, this.Escritorio,this.bd);
        Escritorio.add(ventana);
        ventana.toFront();

    }//GEN-LAST:event_BorraClienteMenuActionPerformed

    private void ListaClientesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaClientesMenuActionPerformed
        ListaClientesInterfaz ventana = new ListaClientesInterfaz();
        this.listaClientes.informacionDeTodosLosClientes(ventana);
        ventana.setVisible(true);
        Escritorio.add(ventana);
        ventana.toFront();


    }//GEN-LAST:event_ListaClientesMenuActionPerformed

    private void ListaVehiculosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaVehiculosMenuActionPerformed
        ListaVehiculosInterfaz ventana = new ListaVehiculosInterfaz();
        this.listaVehiculos.informacionDeTodosLosVehiculos(ventana);
        ventana.setVisible(true);
        Escritorio.add(ventana);
        ventana.toFront();


    }//GEN-LAST:event_ListaVehiculosMenuActionPerformed

    private void BorraVehiculosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorraVehiculosMenuActionPerformed
        BorraVehiculos ventana = new BorraVehiculos(this.listaVehiculos, this.Escritorio,this.bd);
        Escritorio.add(ventana);
        ventana.toFront();

    }//GEN-LAST:event_BorraVehiculosMenuActionPerformed

    private void AltaClientesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaClientesMenuActionPerformed
        AltaClientes ventana = new AltaClientes(this.listaClientes,  this.Escritorio,this.bd);
        Escritorio.add(ventana);
        ventana.toFront();

    }//GEN-LAST:event_AltaClientesMenuActionPerformed

    private void ModificacionClientesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificacionClientesMenuActionPerformed
        ModificaClientes ventana = new ModificaClientes(this.listaClientes,  this.Escritorio,this.bd);
        Escritorio.add(ventana);
        ventana.toFront();

    }//GEN-LAST:event_ModificacionClientesMenuActionPerformed

    private void FinanzasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinanzasMenuActionPerformed
     
            Finanzas ventana = new Finanzas(this.bd);
            Escritorio.add(ventana);
            ventana.toFront();

        


    }//GEN-LAST:event_FinanzasMenuActionPerformed

    private void ConsultaPrecioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPrecioMenuActionPerformed
        ConsultaPrecio ventana = new ConsultaPrecio(this.listaClientes, this.listaVehiculos, this.Escritorio,this.bd);
        this.Escritorio.add(ventana);
        ventana.toFront();


    }//GEN-LAST:event_ConsultaPrecioMenuActionPerformed

    private void AlquilaVehiculoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlquilaVehiculoMenuActionPerformed

        AlquilaVehiculo ventana = new AlquilaVehiculo(this.listaClientes, this.listaVehiculos, this.Escritorio,this.bd);
        this.Escritorio.add(ventana);
        ventana.toFront();


    }//GEN-LAST:event_AlquilaVehiculoMenuActionPerformed

    private void DevuelveVehiculoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevuelveVehiculoMenuActionPerformed
        DevuelveVehiculo ventana = new DevuelveVehiculo(this.listaVehiculos, this.Escritorio,this.bd);
        this.Escritorio.add(ventana);
        ventana.toFront();


    }//GEN-LAST:event_DevuelveVehiculoMenuActionPerformed
     private void fromWindowClosing(java.awt.event.WindowEvent evt){
     this.bd.cierraConexion();
     
     }
    @Override
    public void dispose(){
    this.bd.cierraConexion();
    super.dispose();
    
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlquilaVehiculoMenu;
    private javax.swing.JMenuItem AltaClientesMenu;
    private javax.swing.JMenuItem AltaVehiculosMenu;
    private javax.swing.JMenuItem BorraClienteMenu;
    private javax.swing.JMenuItem BorraVehiculosMenu;
    private javax.swing.JMenuItem ConsultaPrecioMenu;
    private javax.swing.JMenuItem DevuelveVehiculoMenu;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem FinanzasMenu;
    private javax.swing.JMenuItem ListaClientesMenu;
    private javax.swing.JMenuItem ListaVehiculosMenu;
    private javax.swing.JMenu MenuAlquileres;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenu MenuFinanzas;
    private javax.swing.JMenu MenuVehiculos;
    private javax.swing.JMenuItem ModificacionClientesMenu;
    private javax.swing.JMenuItem ModificacionVehiculosMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
