/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames.Vehiculos;

import BaseDeDatos.BaseDeDatos;
import JFrames.Notificacion;
import alquilervehiculos.listas.vehiculos.ListaVehiculos;
import alquilervehiculos.menu.LecturaDatosMenu;
import alquilervehiculos.modelo.alquiler.Alquiler;
import alquilervehiculos.modelo.clientes.Cliente;
import alquilervehiculos.modelo.clientes.DatosCliente;
import alquilervehiculos.modelo.vehiculos.Vehiculo;
import exceptions.FormatoIncorrectoException;
import exceptions.NoExisteException;
import javax.swing.JDesktopPane;

/**
 *
 * @author Adrian
 */
public class BorraVehiculos extends javax.swing.JInternalFrame {

    /**
     * Creates new form BorraVehiculos
     */
    private final JDesktopPane Escritorio;

    private final ListaVehiculos listaVehiculos;
    private final ListaVehiculosInterfaz listaVehiculosInterfaz;
    private BaseDeDatos bd;

    public BorraVehiculos(ListaVehiculos listaVehiculos, JDesktopPane escritorio, BaseDeDatos bd
    ) {
        super("Borrado de Vehiculos", true, true, false, true);
        this.Escritorio = escritorio;
        this.listaVehiculos = listaVehiculos;
        this.bd=bd;
        this.listaVehiculosInterfaz = new ListaVehiculosInterfaz();
        this.listaVehiculos.informacionDeTodosLosVehiculos(this.listaVehiculosInterfaz);
        this.Escritorio.add(this.listaVehiculosInterfaz);
        super.pack();
       
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        matriculaVehiculo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BorraVehiculo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        matriculaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaVehiculoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Matricula");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Borrado de Vehiculo");

        BorraVehiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BorraVehiculo.setText("Borra Vehiculo");
        BorraVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorraVehiculoActionPerformed(evt);
            }
        });

        jLabel5.setText("Selecciona un vehiculo de la lista");

        jLabel9.setText("o escribe su matricula");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(BorraVehiculo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(matriculaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(BorraVehiculo)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matriculaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaVehiculoActionPerformed

    private void BorraVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorraVehiculoActionPerformed
        try {
            this.matriculaVehiculo.setText(this.listaVehiculosInterfaz.datoSeleccionado());
            String matricula = matriculaVehiculo.getText();
            matricula = LecturaDatosMenu.compruebaMatricula(matricula);
            Vehiculo vehiculo = this.listaVehiculos.buscaVehiculo(matricula);//busca vehiculo por matricula
            Alquiler alquiler = vehiculo.getAlquiler();//obtiene el alquiler del vehiculo
            if (alquiler != null) {//si el vehiculo esta alquilado..
                Cliente cliente = alquiler.getCliente();//se obtiene cliente del alquiler

                DatosCliente datos = cliente.getDatos();// se obtienen los datos del cliente

                EliminarVehiculo ventana = new EliminarVehiculo("El vehiculo esta alquilado a: " + datos.getNombre() + " DNI: " + datos.getDni(), "¿Realmente quiere eliminarlo?", matricula, listaVehiculos, Escritorio,this.bd);
                Escritorio.add(ventana);
                this.dispose();
                this.listaVehiculosInterfaz.dispose();

            } else {//si el vehiculo no esta alquilado
                eliminaVehiculo(matricula);
                this.bd.eliminaVehiculoPorMatricula(matricula);
                Notificacion notificacion = new Notificacion("Vehiculo borrado");
                this.Escritorio.add(notificacion);
                notificacion.toFront();
                this.dispose();
                this.listaVehiculosInterfaz.dispose();

            }
        } catch (NoExisteException | FormatoIncorrectoException ex) {
            Notificacion notificacion = new Notificacion(ex.getMessage());
            this.Escritorio.add(notificacion);
            notificacion.toFront();

        }


    }//GEN-LAST:event_BorraVehiculoActionPerformed
    private void eliminaVehiculo(String matricula) {
        int indice = this.listaVehiculos.buscaVehiculoObtieneIndice(matricula);//obtiene el indice para poder borrar el vehiculo
        this.listaVehiculos.borraVehiculo(indice);

    }

    /**
     * @param args the command line arguments
     */
    @Override
    public void dispose() {
        super.dispose();
        this.listaVehiculosInterfaz.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorraVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField matriculaVehiculo;
    // End of variables declaration//GEN-END:variables

}
