/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames.Vehiculos;

import BaseDeDatos.BaseDeDatos;
import JFrames.Notificacion;
import alquilervehiculos.listas.vehiculos.ListaVehiculos;
import alquilervehiculos.listas.vehiculos.VehiculoFactory;
import alquilervehiculos.menu.LecturaDatosMenu;
import alquilervehiculos.modelo.alquiler.Alquiler;
import alquilervehiculos.modelo.vehiculos.EnumVehiculos;
import alquilervehiculos.modelo.vehiculos.Vehiculo;
import exceptions.FormatoIncorrectoException;
import exceptions.NoExisteException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Adrian
 */
public class ModificaVehiculos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificaVehiculos
     */
    private ListaVehiculos listaVehiculos;
    private Vehiculo vehiculo;
    private JDesktopPane Escritorio;
    private final ListaVehiculosInterfaz listaVehiculosInterfaz;
    private BaseDeDatos bd;

    public ModificaVehiculos(ListaVehiculos listaVehiculos,  JDesktopPane Escritorio, BaseDeDatos bd) {
        super("Modifica vehiculos", true, true, false, true);
        this.listaVehiculos = listaVehiculos;
        this.Escritorio = Escritorio;
        this.listaVehiculosInterfaz = new ListaVehiculosInterfaz();
        this.listaVehiculos.informacionDeTodosLosVehiculos(this.listaVehiculosInterfaz);
        this.Escritorio.add(this.listaVehiculosInterfaz);
        this.bd = bd;
        initComponents();
        escondeSliders();
        EnumVehiculos[] valores = EnumVehiculos.values();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel<>(valores);
        this.tipoVehiculo.setModel(modelo);

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        matriculaVehiculo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tipoVehiculo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        panelCoche = new javax.swing.JPanel();
        plazasCoche = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        panelCamion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pmaCamion = new javax.swing.JSpinner();
        panelFurgoneta = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pmaFurgoneta = new javax.swing.JSpinner();
        panelMicrobus = new javax.swing.JPanel();
        plazasMicrobus = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Modifica vehiculo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Matricula del vehiculo a modificar");

        matriculaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaVehiculoActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar vehiculo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de Vehiculo");

        tipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coche", "Microbus", "Furgoneta", "Camion" }));

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        panelCoche.setEnabled(false);

        plazasCoche.setMajorTickSpacing(1);
        plazasCoche.setMaximum(7);
        plazasCoche.setMinimum(1);
        plazasCoche.setMinorTickSpacing(1);
        plazasCoche.setPaintLabels(true);
        plazasCoche.setPaintTicks(true);
        plazasCoche.setSnapToTicks(true);
        plazasCoche.setToolTipText("");

        jLabel6.setText("Plazas");

        javax.swing.GroupLayout panelCocheLayout = new javax.swing.GroupLayout(panelCoche);
        panelCoche.setLayout(panelCocheLayout);
        panelCocheLayout.setHorizontalGroup(
            panelCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCocheLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plazasCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCocheLayout.setVerticalGroup(
            panelCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCocheLayout.createSequentialGroup()
                .addGroup(panelCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plazasCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCamion.setEnabled(false);

        jLabel7.setText("PMA");

        pmaCamion.setModel(new SpinnerNumberModel(0.5, 0, 18.5, 0.1)
        );
        pmaCamion.setName(""); // NOI18N
        pmaCamion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pmaCamionPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panelCamionLayout = new javax.swing.GroupLayout(panelCamion);
        panelCamion.setLayout(panelCamionLayout);
        panelCamionLayout.setHorizontalGroup(
            panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCamionLayout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(54, 54, 54)
                .addComponent(pmaCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        panelCamionLayout.setVerticalGroup(
            panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamionLayout.createSequentialGroup()
                .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(pmaCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        panelFurgoneta.setEnabled(false);

        jLabel8.setText("PMA");

        pmaFurgoneta.setModel(new SpinnerNumberModel(0.5, 0, 1, 0.1)
        );
        pmaFurgoneta.setName(""); // NOI18N
        pmaFurgoneta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pmaFurgonetaPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panelFurgonetaLayout = new javax.swing.GroupLayout(panelFurgoneta);
        panelFurgoneta.setLayout(panelFurgonetaLayout);
        panelFurgonetaLayout.setHorizontalGroup(
            panelFurgonetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFurgonetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(46, 46, 46)
                .addComponent(pmaFurgoneta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        panelFurgonetaLayout.setVerticalGroup(
            panelFurgonetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFurgonetaLayout.createSequentialGroup()
                .addGroup(panelFurgonetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pmaFurgoneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        plazasMicrobus.setMajorTickSpacing(4);
        plazasMicrobus.setMaximum(20);
        plazasMicrobus.setMinimum(1);
        plazasMicrobus.setMinorTickSpacing(1);
        plazasMicrobus.setPaintLabels(true);
        plazasMicrobus.setPaintTicks(true);
        plazasMicrobus.setToolTipText("");

        jLabel4.setText("Plazas");

        javax.swing.GroupLayout panelMicrobusLayout = new javax.swing.GroupLayout(panelMicrobus);
        panelMicrobus.setLayout(panelMicrobusLayout);
        panelMicrobusLayout.setHorizontalGroup(
            panelMicrobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMicrobusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plazasMicrobus, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
        );
        panelMicrobusLayout.setVerticalGroup(
            panelMicrobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMicrobusLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelMicrobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMicrobusLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addComponent(plazasMicrobus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Modificar Vehiculo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(panelMicrobus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton2)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(96, Short.MAX_VALUE)
                    .addComponent(panelCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 58, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(panelFurgoneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 72, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(panelMicrobus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(panelCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelFurgoneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel5.setText("Selecciona un vehiculo de la lista");

        jLabel9.setText("o escribe su matricula");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(matriculaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addContainerGap(219, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(matriculaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(jLabel2)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matriculaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaVehiculoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            this.matriculaVehiculo.setText(this.listaVehiculosInterfaz.datoSeleccionado());
            EnumVehiculos tipoVehiculo = (EnumVehiculos) this.tipoVehiculo.getSelectedItem();

            String matricula = matriculaVehiculo.getText();
            matricula = LecturaDatosMenu.compruebaMatricula(matricula);
            this.vehiculo = this.listaVehiculos.buscaVehiculo(matricula);
            String claseVehiculo = this.vehiculo.getClass().getSimpleName();
            muestraSlider(tipoVehiculo);

        } catch (FormatoIncorrectoException | NoExisteException ex) {
            Notificacion notificacion = new Notificacion(ex.getMessage());
            Escritorio.add(notificacion);
            notificacion.toFront();

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        escondeSliders();
        EnumVehiculos tipoVehiculo = (EnumVehiculos) this.tipoVehiculo.getSelectedItem();
        muestraSlider(tipoVehiculo);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            EnumVehiculos tipoVehiculo = (EnumVehiculos) this.tipoVehiculo.getSelectedItem();

            String claseVehiculo = tipoVehiculo.toString();
            String matricula = matriculaVehiculo.getText();
            matricula = LecturaDatosMenu.compruebaMatricula(matricula);
            int indiceVehiculo = this.listaVehiculos.buscaVehiculoObtieneIndice(matricula);
            String dato = seleccionaDato(tipoVehiculo);

            Vehiculo vehiculoNuevo = VehiculoFactory.getVehiculo(claseVehiculo, matricula, dato);
            Alquiler alquilerOriginal = this.vehiculo.getAlquiler();
            vehiculoNuevo.alquilate(alquilerOriginal);
            this.listaVehiculos.sustituyeVehiculo(indiceVehiculo, vehiculoNuevo);
            this.bd.modificaVehiculoParte1(vehiculo, vehiculoNuevo);
            this.dispose();
            Notificacion notificacion = new Notificacion("Vehiculo modificado");
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        } catch (FormatoIncorrectoException ex) {
            Notificacion notificacion = new Notificacion(ex.getMessage());
            Escritorio.add(notificacion);
            notificacion.toFront();
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void pmaCamionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pmaCamionPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_pmaCamionPropertyChange

    private void pmaFurgonetaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pmaFurgonetaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_pmaFurgonetaPropertyChange
    private void escondeSliders() {
        this.panelCoche.setVisible(false);
        this.panelMicrobus.setVisible(false);
        this.panelFurgoneta.setVisible(false);
        this.panelCamion.setVisible(false);

    }

    private String seleccionaDato(EnumVehiculos tipoVehiculo) {

        switch (tipoVehiculo) {
            case COCHE:
                return String.valueOf(this.plazasCoche.getValue());

            case MICROBUS:
                return String.valueOf(this.plazasMicrobus.getValue());

            case FURGONETA:
                return this.pmaFurgoneta.getValue().toString();

            case CAMION:
                return this.pmaCamion.getValue().toString();
        }
        return "";
    }

    private void muestraSlider(EnumVehiculos tipoVehiculo) {
        switch (tipoVehiculo) {
            case COCHE:
                this.tipoVehiculo.setSelectedIndex(0);
                this.panelCoche.setVisible(true);
                break;
            case MICROBUS:
                this.tipoVehiculo.setSelectedIndex(1);
                this.panelMicrobus.setVisible(true);
                break;
            case FURGONETA:
                this.tipoVehiculo.setSelectedIndex(2);
                this.panelFurgoneta.setVisible(true);
                break;
            case CAMION:
                this.tipoVehiculo.setSelectedIndex(3);
                this.panelCamion.setVisible(true);
                break;
        }

    }

    /**
     * @param args the command line arguments
     */
    @Override
    public void dispose() {
        super.dispose();

        this.listaVehiculosInterfaz.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField matriculaVehiculo;
    private javax.swing.JPanel panelCamion;
    private javax.swing.JPanel panelCoche;
    private javax.swing.JPanel panelFurgoneta;
    private javax.swing.JPanel panelMicrobus;
    private javax.swing.JSlider plazasCoche;
    private javax.swing.JSlider plazasMicrobus;
    private javax.swing.JSpinner pmaCamion;
    private javax.swing.JSpinner pmaFurgoneta;
    private javax.swing.JComboBox<String> tipoVehiculo;
    // End of variables declaration//GEN-END:variables
}
