/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames.Alquileres;

import BaseDeDatos.BaseDeDatos;
import JFrames.Clientes.ListaClientesInterfaz;
import JFrames.Notificacion;
import JFrames.Vehiculos.ListaVehiculosNoAlquiladosInterfaz;
import alquilervehiculos.listas.clientes.ListaClientes;
import alquilervehiculos.listas.vehiculos.ListaVehiculos;
import alquilervehiculos.menu.LecturaDatosMenu;
import alquilervehiculos.modelo.alquiler.Alquiler;
import alquilervehiculos.modelo.clientes.Cliente;
import alquilervehiculos.modelo.vehiculos.Vehiculo;
import exceptions.FormatoIncorrectoException;
import exceptions.NoExisteException;
import exceptions.VehiculoOcupadoException;
import javax.swing.JDesktopPane;

/**
 *
 * @author Adrian
 */
public class AlquilaVehiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlquilaVehiculo
     */
    private Vehiculo vehiculo;
    private ListaVehiculos listaVehiculos;
    private JDesktopPane Escritorio;
    private ListaClientes listaClientes;
    private Cliente cliente;
    private String matriculaString;
    private Integer diasInt;
    private static final int MAX_DIAS_ALQUILER = 365;
    private Alquiler alquiler;
    private double precioAlquiler;
    private BaseDeDatos bd;

    private ListaVehiculosNoAlquiladosInterfaz listaNoAlquilados;
    private ListaClientesInterfaz listaClientesInterfaz;

    public AlquilaVehiculo(ListaClientes listaClientes, ListaVehiculos listaVehiculos, JDesktopPane Escritorio, BaseDeDatos bd) {
        super("Alquila vehiculo", true, true, false, true);
        this.listaClientes = listaClientes;
        this.listaVehiculos = listaVehiculos;
        this.Escritorio = Escritorio;
      
        this.bd=bd;
        this.listaNoAlquilados = new ListaVehiculosNoAlquiladosInterfaz();
        this.listaVehiculos.informacionDeLosVehiculosSinAlquilar(listaNoAlquilados);
        this.Escritorio.add(listaNoAlquilados);
        this.listaClientesInterfaz = new ListaClientesInterfaz();
        this.listaClientes.informacionDeTodosLosClientes(this.listaClientesInterfaz);
        this.Escritorio.add(this.listaClientesInterfaz);

        initComponents();
        this.jPanel4.setVisible(false);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        calculaPrecio = new javax.swing.JButton();
        precio = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pago = new javax.swing.JTextField();
        alquilaVehiculo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Matricula");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matricula))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("DNI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel3.setText("Dias");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Alquiler de vehiculos");

        calculaPrecio.setText("Calcular precio");
        calculaPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPrecioActionPerformed(evt);
            }
        });

        precio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        precio.setText("0 euros");

        jLabel6.setText("¿Cuanto va a pagar?");

        alquilaVehiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alquilaVehiculo.setText("Alquila vehiculo");
        alquilaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alquilaVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(pago, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(alquilaVehiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alquilaVehiculo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Puedes seleccionar de las listas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calculaPrecio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(precio)
                        .addGap(69, 69, 69))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precio)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculaPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculaPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculaPrecioActionPerformed
        try {
            String dni = this.dni.getText();
            if (dni.equals("")) {
                this.dni.setText(this.listaClientesInterfaz.datoSeleccionado());
                            dni=this.dni.getText();

            }
            String matricula = this.matricula.getText();
            if (matricula.equals("")) {
                this.matricula.setText(this.listaNoAlquilados.datoSeleccionado());
                            matricula=this.matricula.getText();

            }
            this.matriculaString = LecturaDatosMenu.compruebaMatricula(matricula);
            this.listaVehiculos.buscaVehiculo(this.matriculaString);

            this.vehiculo = this.listaVehiculos.buscaVehiculoNoAlquilado(this.matriculaString);

            dni = LecturaDatosMenu.leeDni(dni);
            this.cliente = this.listaClientes.buscaCliente(dni);

            Alquiler alquilerOriginal = this.vehiculo.getAlquiler();
            String dias = this.dias.getText();
            this.diasInt = Integer.parseInt(dias);

            this.diasInt = LecturaDatosMenu.compruebaDias(this.diasInt, 1, MAX_DIAS_ALQUILER);

            this.vehiculo.alquilate(this.diasInt, cliente);
            this.alquiler = this.vehiculo.getAlquiler();

            double precioAlquiler = this.vehiculo.calculaPrecioAlquiler(this.diasInt);

            precioAlquiler = this.alquiler.calculaPrecioAlquilerAplicandoDto(this.vehiculo, precioAlquiler);
            precioAlquiler = LecturaDatosMenu.redondearDecimales(precioAlquiler, 2);

            this.precioAlquiler = precioAlquiler;
            this.precio.setText(String.valueOf(precioAlquiler) + " euros");
            this.vehiculo.alquilate(alquilerOriginal);
            this.jPanel4.setVisible(true);

        } catch (NoExisteException | VehiculoOcupadoException | FormatoIncorrectoException ex) {
            Notificacion notificacion = new Notificacion(ex.getMessage());
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        } catch (NumberFormatException ex) {
            Notificacion notificacion = new Notificacion("No es un numero");
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        }


    }//GEN-LAST:event_calculaPrecioActionPerformed

    private void alquilaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alquilaVehiculoActionPerformed

        try {
            double pagoR = Double.parseDouble(this.pago.getText());
            LecturaDatosMenu.consultaPagado(pagoR, this.precioAlquiler);
            this.vehiculo.alquilate(this.alquiler);

            this.vehiculo.realizaPagoSobreAlquiler(pagoR);
            this.bd.alquilaVehiculo(this.cliente, this.vehiculo,pagoR, this.diasInt);
            this.listaNoAlquilados.dispose();
            this.listaClientesInterfaz.dispose();
            this.dispose();
            Notificacion notificacion = new Notificacion("Vehiculo alquilado");
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        } catch (FormatoIncorrectoException ex) {
            Notificacion notificacion = new Notificacion(ex.getMessage());
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        } catch (NumberFormatException ex) {
            Notificacion notificacion = new Notificacion("No es un numero");
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        }


    }//GEN-LAST:event_alquilaVehiculoActionPerformed

    @Override
    public void dispose() {

        super.dispose();
        this.listaClientesInterfaz.dispose();
        this.listaNoAlquilados.dispose();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alquilaVehiculo;
    private javax.swing.JButton calculaPrecio;
    private javax.swing.JTextField dias;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField pago;
    private javax.swing.JLabel precio;
    // End of variables declaration//GEN-END:variables
}
