/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames.Alquileres;

import BaseDeDatos.BaseDeDatos;
import JFrames.Clientes.ListaClientesInterfaz;
import JFrames.Notificacion;
import JFrames.Vehiculos.ListaVehiculosNoAlquiladosInterfaz;
import alquilervehiculos.listas.clientes.ListaClientes;
import alquilervehiculos.listas.vehiculos.ListaVehiculos;
import alquilervehiculos.menu.LecturaDatosMenu;
import alquilervehiculos.modelo.alquiler.Alquiler;
import alquilervehiculos.modelo.clientes.Cliente;
import alquilervehiculos.modelo.vehiculos.Vehiculo;
import exceptions.FormatoIncorrectoException;
import exceptions.NoExisteException;
import exceptions.VehiculoOcupadoException;

import javax.swing.JDesktopPane;

/**
 *
 * @author Adrian
 */
public class ConsultaPrecio extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaPrecio
     */
    private JDesktopPane Escritorio;

    private static final int MAX_DIAS_ALQUILER = 365;
    private ListaVehiculos listaVehiculos;
    private ListaClientes listaClientes;
    private String matriculaString;
    private Cliente cliente;
    private Integer diasInt;
    private Vehiculo vehiculo;
    private Double precioFinal;
    private BaseDeDatos bd;

    private ListaVehiculosNoAlquiladosInterfaz listaNoAlquilados;
    private ListaClientesInterfaz listaClientesInterfaz;

    public ConsultaPrecio(ListaClientes listaClientes, ListaVehiculos listaVehiculos, JDesktopPane Escritorio,BaseDeDatos bd) {
        super("Consulta precio", true, true, false, true);
        this.listaVehiculos = listaVehiculos;
        this.Escritorio = Escritorio;
        this.listaClientes = listaClientes;
        this.bd=bd;
        this.listaNoAlquilados = new ListaVehiculosNoAlquiladosInterfaz();
        this.listaVehiculos.informacionDeLosVehiculosSinAlquilar(listaNoAlquilados);
        this.Escritorio.add(listaNoAlquilados);

        initComponents();
        this.AlquilarPanel.setVisible(false);

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConsultarPrecio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dias = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        PrecioProvisional = new javax.swing.JLabel();
        AlquilarPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ConsultaPrecioFinal = new javax.swing.JButton();
        dni = new javax.swing.JTextField();
        Alquilar = new javax.swing.JButton();
        PrecioFinal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pagado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        ConsultarPrecio.setText("Consultar precio");
        ConsultarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarPrecioActionPerformed(evt);
            }
        });

        jLabel1.setText("Matricula");

        jLabel2.setText("Dias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConsultarPrecio)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConsultarPrecio)
                .addContainerGap())
        );

        PrecioProvisional.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PrecioProvisional.setText("0 euros");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(PrecioProvisional)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(PrecioProvisional)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("DNI");

        ConsultaPrecioFinal.setText("Consulta precio final");
        ConsultaPrecioFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPrecioFinalActionPerformed(evt);
            }
        });

        Alquilar.setText("Alquilar");
        Alquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlquilarActionPerformed(evt);
            }
        });

        PrecioFinal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PrecioFinal.setText("0 euros");

        jLabel5.setText("¿Cuanto desea pagar?");

        jLabel7.setText("Puedes seleccionar de la lista");

        javax.swing.GroupLayout AlquilarPanelLayout = new javax.swing.GroupLayout(AlquilarPanel);
        AlquilarPanel.setLayout(AlquilarPanelLayout);
        AlquilarPanelLayout.setHorizontalGroup(
            AlquilarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlquilarPanelLayout.createSequentialGroup()
                .addGroup(AlquilarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AlquilarPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagado, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Alquilar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AlquilarPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(AlquilarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AlquilarPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(AlquilarPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ConsultaPrecioFinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(PrecioFinal)))))
                .addGap(33, 33, 33))
        );
        AlquilarPanelLayout.setVerticalGroup(
            AlquilarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlquilarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AlquilarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioFinal)
                    .addComponent(ConsultaPrecioFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlquilarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alquilar)
                    .addComponent(jLabel5)
                    .addComponent(pagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Consulta precio de alquiler");

        jLabel6.setText("Puedes seleccionar de la lista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AlquilarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlquilarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarPrecioActionPerformed

        try {
            String matricula = this.matricula.getText();
            if (matricula.equals("")) {
                this.matricula.setText(this.listaNoAlquilados.datoSeleccionado());
                            matricula=this.matricula.getText();

            }
            this.matriculaString = LecturaDatosMenu.compruebaMatricula(matricula);
            
            this.listaVehiculos.buscaVehiculo(this.matriculaString);
            // Se considera que no se puede alquilar un vehículo más de 365 días
            String dias = this.dias.getText();
            this.diasInt = Integer.parseInt(dias);

            this.diasInt = LecturaDatosMenu.compruebaDias(this.diasInt, 1, MAX_DIAS_ALQUILER);

            if (this.diasInt != null) {
                muestraResultadoDeObtenerPrecioAlquiler(this.matriculaString, this.diasInt);
                this.listaClientesInterfaz = new ListaClientesInterfaz();
                this.listaClientes.informacionDeTodosLosClientes(this.listaClientesInterfaz);
                this.Escritorio.add(this.listaClientesInterfaz);

            }
        } catch (FormatoIncorrectoException ex) {
            Notificacion notificacion = new Notificacion(ex.getMessage());
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        } catch (NumberFormatException ex) {
            Notificacion notificacion = new Notificacion("No es un numero");
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        } catch (NoExisteException ex) {
            Notificacion notificacion = new Notificacion(ex.getMessage());
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        }


    }//GEN-LAST:event_ConsultarPrecioActionPerformed

    private void AlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlquilarActionPerformed

        Alquiler alquilerOriginal = this.vehiculo.getAlquiler();
        if (alquilerOriginal == null) {

            try {

                double pago = Double.parseDouble(this.pagado.getText());
                LecturaDatosMenu.consultaPagado(pago, this.precioFinal);

                this.vehiculo.alquilate(this.diasInt, cliente);
                this.vehiculo.realizaPagoSobreAlquiler(pago);
                this.bd.alquilaVehiculo(this.cliente,this.vehiculo,pago,this.diasInt);
                Notificacion notificacion = new Notificacion("Vehiculo alquilado");
                this.Escritorio.add(notificacion);
                notificacion.toFront();
                this.listaNoAlquilados.dispose();
                this.listaClientesInterfaz.dispose();
                this.dispose();
            } catch (FormatoIncorrectoException ex) {
                Notificacion notificacion = new Notificacion(ex.getMessage());
                this.Escritorio.add(notificacion);
                notificacion.toFront();
            }
        } else {
            try {
                throw new VehiculoOcupadoException("El vehiculo esta alquilado");
            } catch (VehiculoOcupadoException ex) {
                Notificacion notificacion = new Notificacion(ex.getMessage());
                this.Escritorio.add(notificacion);
                notificacion.toFront();

            }
        }


    }//GEN-LAST:event_AlquilarActionPerformed

    private void ConsultaPrecioFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPrecioFinalActionPerformed
        try {
            dni.setText(this.listaClientesInterfaz.datoSeleccionado());
            this.vehiculo = this.listaVehiculos.buscaVehiculoNoAlquilado(this.matriculaString);

            String dni = this.dni.getText();
            dni = LecturaDatosMenu.leeDni(dni);
            this.cliente = this.listaClientes.buscaCliente(dni);
            Alquiler alquilerOriginal = this.vehiculo.getAlquiler();

            this.vehiculo.alquilate(this.diasInt, cliente);
            Alquiler alquiler = this.vehiculo.getAlquiler();

            double precioAlquiler = this.vehiculo.calculaPrecioAlquiler(this.diasInt);

            precioAlquiler = alquiler.calculaPrecioAlquilerAplicandoDto(this.vehiculo, precioAlquiler);
            precioAlquiler = LecturaDatosMenu.redondearDecimales(precioAlquiler, 2);

            this.precioFinal = precioAlquiler;
            this.PrecioFinal.setText(String.valueOf(precioAlquiler) + " euros");
            this.vehiculo.alquilate(alquilerOriginal);
            this.Alquilar.setVisible(true);
            this.jLabel5.setVisible(true);
            this.pagado.setVisible(true);

        } catch (NoExisteException | VehiculoOcupadoException | FormatoIncorrectoException ex) {
            Notificacion notificacion = new Notificacion(ex.getMessage());
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        } catch (NumberFormatException ex) {
            Notificacion notificacion = new Notificacion("No es un numero");
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        }


    }//GEN-LAST:event_ConsultaPrecioFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    private void muestraResultadoDeObtenerPrecioAlquiler(String matricula, int numDias) {

        try {
            Double precioAlquiler = this.listaVehiculos.obtienePrecioAlquiler(matricula, numDias);
            this.PrecioProvisional.setText(String.valueOf(precioAlquiler + " euros"));
            this.AlquilarPanel.setVisible(true);
            this.Alquilar.setVisible(false);
            this.jLabel5.setVisible(false);
            this.pagado.setVisible(false);

        } catch (NoExisteException ex) {
            Notificacion notificacion = new Notificacion(ex.getMessage());
            this.Escritorio.add(notificacion);
            notificacion.toFront();
        }
    }

    @Override
    public void dispose() {
        super.dispose();
        this.listaNoAlquilados.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alquilar;
    private javax.swing.JPanel AlquilarPanel;
    private javax.swing.JButton ConsultaPrecioFinal;
    private javax.swing.JButton ConsultarPrecio;
    private javax.swing.JLabel PrecioFinal;
    private javax.swing.JLabel PrecioProvisional;
    private javax.swing.JTextField dias;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField pagado;
    // End of variables declaration//GEN-END:variables
}
